version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: env-builds
      - deploy:
          requires:
            - build

jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: whoami
          command: whoami
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Building
          command: |
            node --version
            npm --version
            npm install reactjs
            npx browserslist@latest --update-db
            npm run build:dev
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
  deploy:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: root
      - run:
          name: whoami
          command: whoami
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Upload
          command: |
            ls -la
            awscli --version