version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            node --version
            npm --version