version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

env:
  CI: false

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: env-builds

jobs:
  build:
    docker:
      - image: node:lts
    working_directory: ~/admin-webapp
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            node --version
            npm --version
            npm install reactjs
            npx browserslist@latest --update-db
            npm run build
      - run:
          name: ls -la
          command: ls -la