version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: env-builds

jobs:
  build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            node --version
            npm --version